export const collections = [
    {
        code: "SciHub/S1",
        satellites: ['s1a','s1b'],
        cycle: 1000*60*60*24*12,
        // cycle: (1000*60*60*24*75)/14.5919788,
        templateUrl: 'https://scihub.copernicus.eu/dhus/search?q=( footprint:"Intersects({polygon})" AND beginposition:[{start} TO {end}] AND platformname:Sentinel-1  AND filename:*{freetext}*)&start={startindex}&rows=100&orderby=beginposition desc&format=json',
        name: 'SciHub/S1' ,
        logo: './images/s1_black.png',
        type: 'DHUS',
        startIndexOrigin: 0,
        dateOff: " beginposition:[{start} TO {end}] AND",
        areaOff: ' footprint:"Intersects({polygon})" AND',
        windowSize: 1000 * 60 * 60 * 18,
        defaultFreetext: 'GRD'
    },
    {
        code: 'SciHub/S2',
        satellites: ['s2a','s2b'],
        // cycle: (1000*60*60*24*143)/14.308183,
        cycle: (1000*60*60*24*10),
        templateUrl: 'https://scihub.copernicus.eu/dhus/search?q=( footprint:"Intersects({polygon})" AND beginposition:[{start} TO {end}] AND platformname:Sentinel-2 AND filename:*{freetext}*)&start={startindex}&rows=100&orderby=beginposition desc&format=json',
        name: 'SciHub/S2',
        logo: './images/s2_black.png',
        type: 'DHUS',
        startIndexOrigin: 0,
        dateOff: ' beginposition:[{start} TO {end}] AND',
        areaOff:  ' footprint:"Intersects({polygon})" AND',
        windowSize: 1000 * 60 * 60 *3,
        defaultFreetext: 'S2A_MSIL1C' 
    },
    {
        code: 'SciHub/S3',
        satellites: ['s3a','s3b'],
        cycle: (1000*60*60*24*27),
        templateUrl: 'https://scihub.copernicus.eu/dhus/search?q=( footprint:"Intersects({polygon})" AND beginposition:[{start} TO {end}] AND platformname:Sentinel-3 AND (producttype:OL_1_LFR___ OR producttype:SL_1_RBT___ OR producttype:SR_1_SRA___))&start={startindex}&rows=100&orderby=beginposition desc&format=json',
        name: 'Sentinel-3 A/B, OLCI/SLSTR/SRAL' ,
        logo: './images/s3_black.png',
        type: 'DHUS',
        startIndexOrigin: 0,
        dateOff: ' beginposition:[{start} TO {end}] AND',
        areaOff:  ' footprint:"Intersects({polygon})" AND',
        windowSize: 1000 * 60 * 60 * 24
    },
    {
        code: 'SciHub/S3A/OLCI/LFR',
        satellites: ['s3a'],
        cycle: (1000*60*60*24*27),
        templateUrl: 'https://scihub.copernicus.eu/dhus/search?q=( footprint:"Intersects({polygon})" AND beginposition:[{start} TO {end}] AND platformname:Sentinel-3 AND filename:S3A_*  AND (producttype:OL_2_LFR___))&start={startindex}&rows=100&orderby=beginposition desc&format=json',
        name: 'Sentinel-3 A, OLCI/LFR' ,
        logo: './images/s3_black.png',
        type: 'DHUS',
        startIndexOrigin: 0,
        dateOff: ' beginposition:[{start} TO {end}] AND',
        areaOff:  ' footprint:"Intersects({polygon})" AND',
        windowSize: 1000 * 60 * 60 * 24
    },
    {
        code: 'SciHub/S3B/OLCI/LFR',
        satellites: ['s3b'],
        cycle: (1000*60*60*24*27),
        templateUrl: 'https://scihub.copernicus.eu/dhus/search?q=( footprint:"Intersects({polygon})" AND beginposition:[{start} TO {end}] AND platformname:Sentinel-3 AND filename:S3B_* AND (producttype:OL_2_LFR___))&start={startindex}&rows=100&orderby=beginposition desc&format=json',
        name: 'Sentinel-3 B, OLCI/LFR' ,
        logo: './images/s3_black.png',
        type: 'DHUS',
        startIndexOrigin: 0,
        dateOff: ' beginposition:[{start} TO {end}] AND',
        areaOff:  ' footprint:"Intersects({polygon})" AND',
        windowSize: 1000 * 60 * 60 * 24
    },
    {
        code: 'SciHub2/S3',
        templateUrl: 'https://scihub.copernicus.eu/dhus/search?q=( footprint:"Intersects({polygon})" AND beginposition:[{start} TO {end}] AND platformname:Sentinel-3 AND (producttype:{freetext}))&start={startindex}&rows=100&orderby=beginposition desc&format=json',
        satellites: ['s3a','s3b'],
        cycle: (1000*60*60*24*27),
        name: 'SciHub2/S3' ,
        logo: './images/s3_black.png',
        type: 'DHUS',
        startIndexOrigin: 0,
        dateOff: ' beginposition:[{start} TO {end}] AND',
        areaOff:  ' footprint:"Intersects({polygon})" AND',
        windowSize: 1000 * 60 * 60 * 24,
        defaultFreetext: 'SR_1_SRA___'
    },
    {
        code: 'SciHub/S5P',
        satellites: ['s5p'],
        cycle: (1000*60*60*24*16),
        templateUrl: 'https://scihub.copernicus.eu/dhus/search?q=( footprint:"Intersects({polygon})" AND beginposition:[{start} TO {end}] AND platformname:Sentinel-5 precursor AND producttype:{freetext}))&start={startindex}&rows=100&orderby=beginposition desc&format=json',
        name: 'S5P',
        logo: './images/s5p_black.png',
        type: 'DHUS',
        startIndexOrigin: 0,
        dateOff: ' beginposition:[{start} TO {end}] AND',
        areaOff:  ' footprint:"Intersects({polygon})" AND',
        windowSize: 1000 * 60 * 60 * 24,
        defaultFreetext: 'L1B_RA_BD1'
    },
    {
        code: 'EODC-DHR/Envisat',
        satellites: ['env'],
        cycle: (1000*60*60*24*35),
        templateUrl: 'https://dhr.datahub.eodc.eu/search?q=( footprint:"Intersects({polygon})" AND beginposition:[{start} TO {end}] AND platformname:Envisat AND producttype:{freetext}) &start={startindex}&rows=100&orderby=beginposition desc&format=json',
        name: "EODC-DHR/Envisat",
        logo: './images/s5p_black.png',
        type: 'DHUS',
        startIndexOrigin: 0,
        dateOff: ' beginposition:[{start} TO {end}] AND',
        areaOff:  ' footprint:"Intersects({polygon})" AND',
        windowSize: 1000 * 60 * 60 * 24,
        defaultFreetext: 'MER_FRS_2P'
    },
    {
        code: 'EOCAT Meris',
        satellites: ['env'],
        templateUrl: 'https://eocat.esa.int/api/catalogue/EOCAT-{freetext}/search?start={start}&stop={end}&geom={polygon}&format=json&count=50&startIndex={startindex}',
        startIndexOrigin: 1,
        name: 'EOCAT-MER_FRS_2P',
        logo: './images/s5p_black.png',
        type: 'EOCAT',
        dateOff: 'start={start}&stop={end}&',
        areaOff:  '&geom={polygon}',
        windowSize: 1000 * 60 * 60 * 24 * 3,
        defaultFreetext: 'MER_FRS_2P'
    },

    {
        code: 'EOCAT ASA',
        satellites: ['env'],
        templateUrl: 'https://eocat.esa.int/api/catalogue/EOCAT-{freetext}/search?start={start}&stop={end}&geom={polygon}&format=json&count=50&startIndex={startindex}',
        startIndexOrigin: 1,
        name: 'EOCAT-ENVISAT.ASA.IMP_1P',
        logo: './images/s5p_black.png',
        type: 'EOCAT',
        dateOff: 'start={start}&stop={end}&',
        areaOff:  '&geom={polygon}',
        windowSize: 1000 * 60 * 60 * 24 * 3,
        defaultFreetext: 'ENVISAT.ASA.IMP_1P'
    },

    // {
    //     code: 'RefSysStac',
    //     templateUrl: 'https://processing.platform.ops-csc.com/native-api/stac/search?datetime={start}/{end}',
    //     satellites: ['s1a'],
    //     cycle: (1000*60*60*24)/14.308183,
    //     startIndexOrigin: 1,
    //     name: 'RS Stac',
    //     type: 'STAC',
    //     logo: './images/s5p_black.png',
    //     dateOff: 'datetime={start}/{end}',
    //     areaOff:  ' and OData.CSC.Intersects(area=geography%27SRID=4326;{polygon}%27)',
    //     windowSize: 1000 * 60 * 60 * 24 * 3
    // },

    {
        code: 'RefSys1',
        satellites: ['s1a'],
        cycle: 1000*60*60*24*12,
        templateUrl: 'https://processing.platform.ops-csc.com/ddip/odata/v1/Products?$format=json&$count=true&$top=100&$skip={startindex}&$filter=contains(Name,%27{freetext}%27)%20and%20OData.CSC.Intersects(area=geography%27SRID=4326;{polygon}%27)%20and%20ContentDate/Start%20gt%20{start}%20and%20ContentDate/Start%20lt%20{end}&$orderby=%20ContentDate/Start%20desc',
        tokenEndpoint: 'https://iam.platform.ops-csc.com/auth/realms/RS/protocol/openid-connect/token',
        grantType: 'client_credentials',
        startIndexOrigin: 0,
        name: 'RefSys',
        logo: './images/s1_black.png',
        type: 'PRIP',
        dateOff: '%20and%20ContentDate/Start%20gt%20{start}%20and%20ContentDate/Start%20lt%20{end}',
        areaOff:  '%20and%20OData.CSC.Intersects(area=geography%27SRID=4326;{polygon}%27)',
        windowSize: 1000 * 60 * 60 * 24 * 100,
        defaultFreetext: 'S1A_IW_RAW__0SDV'
    },

    {
        code: 'RefSys2',
        satellites: ['s1a'],
        cycle: 1000*60*60*24*12,
        templateUrl: 'https://processing.platform.ops-csc.com/ddip/odata/v1/Products?$format=json&$count=true&$top=100&$skip={startindex}&$filter=contains(Name,%27{freetext}%27)%20and%20OData.CSC.Intersects(area=geography%27SRID=4326;{polygon}%27)%20and%20ContentDate/Start%20gt%20{start}%20and%20ContentDate/Start%20lt%20{end}&$orderby=%20ContentDate/Start%20desc',
        tokenEndpoint: 'https://iam.platform.ops-csc.com/auth/realms/RS/protocol/openid-connect/token',
        grantType: 'client_credentials',
        startIndexOrigin: 0,
        name: 'RefSys',
        logo: './images/s1_black.png',
        type: 'PRIP',
        dateOff: '%20and%20ContentDate/Start%20gt%20{start}%20and%20ContentDate/Start%20lt%20{end}',
        areaOff:  '%20and%20OData.CSC.Intersects(area=geography%27SRID=4326;{polygon}%27)',
        windowSize: 1000 * 60 * 60 * 24 * 100,
        defaultFreetext: 'EW_RAW__0N'
    },

    


    {
        code: 'RefSys3',
        satellites: ['s3a','s3b'],
        cycle: (1000*60*60*24*27),
        templateUrl: 'https://processing.platform.ops-csc.com/ddip/odata/v1/Products?$format=json&$count=true&$top=100&$skip={startindex}&$filter=contains(Name,%27{freetext}%27)%20and%20OData.CSC.Intersects(area=geography%27SRID=4326;{polygon}%27)%20and%20ContentDate/Start%20gt%20{start}%20and%20ContentDate/Start%20lt%20{end}&$orderby=%20ContentDate/Start%20desc',
        tokenEndpoint: 'https://iam.platform.ops-csc.com/auth/realms/RS/protocol/openid-connect/token',
        grantType: 'client_credentials',
        startIndexOrigin: 0,
        name: 'RefSys',
        logo: './images/s5p_black.png',
        type: 'PRIP',
        dateOff: '%20and%20ContentDate/Start%20gt%20{start}%20and%20ContentDate/Start%20lt%20{end}',
        areaOff:  '%20and%20OData.CSC.Intersects(area=geography%27SRID=4326;{polygon}%27)',
        windowSize: 1000 * 60 * 60 * 24 * 7,
        defaultFreetext: 'S3A_SR_0_SRA'
    },

    {
        code: 'RefSys4',
        satellites: ['s2a','s2b'],
        cycle: (1000*60*60*24*10),
        templateUrl: 'https://processing.platform.ops-csc.com/ddip/odata/v1/Products?$format=json&$count=true&$top=100&$skip={startindex}&$filter=contains(Name,%27{freetext}%27)%20and%20OData.CSC.Intersects(area=geography%27SRID=4326;{polygon}%27)%20and%20ContentDate/Start%20gt%20{start}%20and%20ContentDate/Start%20lt%20{end}&$orderby=%20ContentDate/Start%20desc',
        tokenEndpoint: 'https://iam.platform.ops-csc.com/auth/realms/RS/protocol/openid-connect/token',
        // grantType: 'client_credentials',
        grantType: 'client_credentials',
        startIndexOrigin: 0,
        name: 'RefSys',
        logo: './images/s2_black.png',
        type: 'PRIP',
        dateOff: '%20and%20ContentDate/Start%20gt%20{start}%20and%20ContentDate/Start%20lt%20{end}',
        areaOff:  '%20and%20OData.CSC.Intersects(area=geography%27SRID=4326;{polygon}%27)',
        windowSize: 1000 * 60 * 60 * 24 * 7,
        defaultFreetext: 'MSI_L1C_TL'
    },

    {
        code: 'RefSys5',
        satellites: ['s2a','s2b'],
        cycle: (1000*60*60*24*10),
        templateUrl: 'https://processing.platform.ops-csc.com/ddip/odata/v1/Products?$format=json&$count=true&$top=100&$skip={startindex}&$filter=contains(Name,%27{freetext}%27)%20and%20OData.CSC.Intersects(area=geography%27SRID=4326;{polygon}%27)%20and%20ContentDate/Start%20gt%20{start}%20and%20ContentDate/Start%20lt%20{end}&$orderby=%20ContentDate/Start%20desc',
        tokenEndpoint: 'https://iam.platform.ops-csc.com/auth/realms/RS/protocol/openid-connect/token',
        grantType: 'client_credentials',
        startIndexOrigin: 0,
        name: 'RefSys',
        logo: './images/s2_black.png',
        type: 'PRIP',
        dateOff: '%20and%20ContentDate/Start%20gt%20{start}%20and%20ContentDate/Start%20lt%20{end}',
        areaOff:  '%20and%20OData.CSC.Intersects(area=geography%27SRID=4326;{polygon}%27)',
        windowSize: 1000 * 60 * 60 * 24 * 7,
        defaultFreetext: 'MSI_L2A_DS'
    },

    {
        code: 'RefSys6',
        satellites: ['s1a'],
        cycle: (1000*60*60*24*10),
        templateUrl: 'https://processing.platform.ops-csc.com/ddip/odata/v1/Products?$format=json&$count=true&$top=100&$skip={startindex}&$filter=contains(Name,%27{freetext}%27)%20and%20OData.CSC.Intersects(area=geography%27SRID=4326;{polygon}%27)%20and%20ContentDate/Start%20gt%20{start}%20and%20ContentDate/Start%20lt%20{end}&$orderby=%20ContentDate/Start%20desc',
        tokenEndpoint: 'https://iam.platform.ops-csc.com/auth/realms/RS/protocol/openid-connect/token',
        grantType: 'client_credentials',
        startIndexOrigin: 0,
        name: 'RefSys',
        logo: './images/s2_black.png',
        type: 'PRIP',
        dateOff: '%20and%20ContentDate/Start%20gt%20{start}%20and%20ContentDate/Start%20lt%20{end}',
        areaOff:  '%20and%20OData.CSC.Intersects(area=geography%27SRID=4326;{polygon}%27)',
        windowSize: 1000 * 60 * 60 * 24 * 7,
        defaultFreetext: 'S1__AUX_WAV'
    },

    {
        code: 'LTA',
        satellites: ['s1a','s1b','s2a','s2b','s3a','s3b'],
        cycle: (1000*60*60*24*10),
        templateUrl: 'https://lta.acri.copernicus.eu/odata/v1/Products?$count=true&$top=100&$skip={startindex}&$filter=contains(Name,%27{freetext}%27)%20and%20OData.CSC.Intersects(area=geography%27SRID=4326;{polygon}%27)%20and%20ContentDate/Start%20gt%20{start}%20and%20ContentDate/Start%20lt%20{end}',
        startIndexOrigin: 0,
        name: 'LTA Acri',
        logo: './images/s2_black.png',
        type: 'LTA',
        dateOff: '%20and%20ContentDate/Start%20gt%20{start}%20and%20ContentDate/Start%20lt%20{end}',
        areaOff:  '%20and%20OData.CSC.Intersects(area=geography%27SRID=4326;{polygon}%27)',
        windowSize: 1000 * 60 * 60 * 24 ,
        defaultFreetext: 'EW_RAW__0N'
    },

    {
        code: 'CDSE',
        satellites: ['s1a','s1b','s2a','s2b','s3a','s3b'],
        cycle: (1000*60*60*24*10),
        templateUrl: 'https://catalogue.dataspace.copernicus.eu/odata/v1/Products?$count=true&$top=100&$skip={startindex}&$filter=contains(Name,%27{freetext}%27)%20and%20OData.CSC.Intersects(area=geography%27SRID=4326;{polygon}%27)%20and%20ContentDate/Start%20gt%20{start}%20and%20ContentDate/Start%20lt%20{end}&$expand=Assets',
        tokenEndpoint: 'https://identity.dataspace.copernicus.eu/auth/realms/CDSE/protocol/openid-connect/token',
        grantType: 'password',
        startIndexOrigin: 0,
        name: 'CDSE',
        logo: './images/s2_black.png',
        type: 'CDSEOdata',
        dateOff: '%20and%20ContentDate/Start%20gt%20{start}%20and%20ContentDate/Start%20lt%20{end}',
        areaOff:  '%20and%20OData.CSC.Intersects(area=geography%27SRID=4326;{polygon}%27)',
        windowSize: 1000 * 60 * 60 * 24 ,
        defaultFreetext: 'GRD'
    },

    {
        code: 'CDSE2',
        satellites: ['s1a','s1b','s2a','s2b','s3a','s3b'],
        cycle: (1000*60*60*24*10),
        templateUrl: 'https://catalogue.dataspace.copernicus.eu/stac/search?&datetime={start}/{end}&sortby=-start_datetime&limit=100&page={page}',
        tokenEndpoint: 'https://identity.dataspace.copernicus.eu/auth/realms/CDSE/protocol/openid-connect/token',
        grantType: 'password',
        startIndexOrigin: 1,
        name: 'CDSE STAC',
        logo: './images/s2_black.png',
        type: 'CDSEStac',
        dateOff: '&datetime={start}/{end}',
        areaOff:  '%20and%20OData.CSC.Intersects(area=geography%27SRID=4326;{polygon}%27)',
        windowSize: 1000 * 60 * 60 * 24 ,
        defaultFreetext: 'not in use'
    },

    {
        code: 'CDSE3',
        satellites: ['s1a','s1b','s2a','s2b','s3a','s3b'],
        cycle: (1000*60*60*24*10),
        templateUrl: 'https://catalogue.dataspace.copernicus.eu/stac/collections/{freetext}/items?&datetime={start}/{end}&sortby=-start_datetime&limit=100&page={page}',
        tokenEndpoint: 'https://identity.dataspace.copernicus.eu/auth/realms/CDSE/protocol/openid-connect/token',
        grantType: 'password',
        startIndexOrigin: 1,
        name: 'CDSE STAC',
        logo: './images/s2_black.png',
        type: 'CDSEStac',
        dateOff: '&datetime={start}/{end}',
        areaOff:  '%20and%20OData.CSC.Intersects(area=geography%27SRID=4326;{polygon}%27)',
        windowSize: 1000 * 60 * 60 * 24 ,
        defaultFreetext: 'SENTINEL-1'
    },


    {
        code: 'CDSE1',
        satellites: ['s1a','s1b','s2a','s2b','s3a','s3b'],
        cycle: (1000*60*60*24*10),
        templateUrl: 'https://catalogue.dataspace.copernicus.eu/resto/api/collections/Sentinel2/search.json?startDate={start}&completionDate={end}&sortParam=startDate&maxRecords=100&page={startindex}&$expand=Assets',
        tokenEndpoint: 'https://identity.dataspace.copernicus.eu/auth/realms/CDSE/protocol/openid-connect/token',
        grantType: 'password',
        startIndexOrigin: 1,
        name: 'CDSE OpenSearch',
        logo: './images/s2_black.png',
        type: 'CDSE',
        dateOff: '%20and%20ContentDate/Start%20gt%20{start}%20and%20ContentDate/Start%20lt%20{end}',
        areaOff:  '%20and%20OData.CSC.Intersects(area=geography%27SRID=4326;{polygon}%27)',
        windowSize: 1000 * 60 * 60 * 24 ,
        defaultFreetext: 'EW_RAW__0N'
    }



]